---
 - import_playbook: apt_update.yml

 - hosts: all
   tasks:
     - name: Wait for the reboot and reconnect 
       wait_for:
         port: 22
         host: '{{(ansible_ssh_host|default(ansible_host))|default(inventory_hostname)}}'
         search_regex: OpenSSH
         delay: 10
         timeout: 60
       connection: local

 - import_playbook: build_out_routers.yml
