---
all:
  hosts:
    dnetone:
      vars:
        network_interfaces_template: dnetone/network_interfaces.js
        dnsmasq_conf_template: dnetone/dnsmasq_conf.js
        networking_restart_command: bash -c 'ifdown enp7s0 && ifup enp7s0'
        rules_v4_template: dnetone/iptables_rules_v4.js
    dnettwo:
      vars:
        network_interfaces_template: dnettwo/network_interfaces.js
        dnsmasq_conf_template: dnettwo/dnsmasq_conf.js
        networking_restart_command: bash -c 'ifdown enp7s0 && ifup enp7s0 && ifdown enp8s0 && ifup enp8s0'
        ifup_script_template: dnettwo/ifup-script.js
        rules_v4_template: dnettwo/iptables_rules_v4.js
    dnetthree:
      vars:
        network_interfaces_template: lower_net/network_interfaces.js
        networking_restart_command: bash -c 'ifdown enp7s0 && ifup enp7s0'
        ifup_script_template: lower_net/ifup-script.js
    dnetfour:
      vars:
        network_interfaces_template: lower_net/network_interfaces.js
        networking_restart_command: bash -c 'ifdown enp7s0 && ifup enp7s0'
        ifup_script_template: lower_net/ifup-script.js
    dnetfive:
      vars:
        network_interfaces_template: lower_net/network_interfaces.js
        networking_restart_command: bash -c 'ifdown enp7s0 && ifup enp7s0'
        ifup_script_template: lower_net/ifup-script.js
